sudo: required
dist: trusty
language: node_js
node_js:
  - '7.7'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - node -v
  - npm -v
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install
  - ng build

script: 
  - karma start karma.conf.js --single-run

after_script: 
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
